# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/

app = "epub2kobo"  # your app name could vary
primary_region = "nrt"  # Tokyo, Japan

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"

[deploy]
  strategy = "immediate"
  
[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
  count = 1  # Exactly 1 machine

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[http_service]
  internal_port = 3001
  force_https = true

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/static/upload.html"
